/* soapBasicHttpBinding_USCOREIOGServiceProxy.h
   Generated by gSOAP 2.8.36 for OGService.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapBasicHttpBinding_USCOREIOGServiceProxy_H
#define soapBasicHttpBinding_USCOREIOGServiceProxy_H
#include "soapH.h"

    class SOAP_CMAC BasicHttpBinding_USCOREIOGServiceProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        bool soap_own; ///< flag indicating that this context is owned by this proxy when context is shared
        /// Endpoint URL of service 'BasicHttpBinding_USCOREIOGServiceProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in OGService.h, if any
        /// Construct a proxy with new managing context
        BasicHttpBinding_USCOREIOGServiceProxy();
        /// Copy constructor
        BasicHttpBinding_USCOREIOGServiceProxy(const BasicHttpBinding_USCOREIOGServiceProxy& rhs);
        /// Construct proxy given a shared managing context
        BasicHttpBinding_USCOREIOGServiceProxy(struct soap*);
        /// Constructor taking an endpoint URL
        BasicHttpBinding_USCOREIOGServiceProxy(const char *endpoint);
        /// Constructor taking input and output mode flags for the new managing context
        BasicHttpBinding_USCOREIOGServiceProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        BasicHttpBinding_USCOREIOGServiceProxy(const char *endpoint, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        BasicHttpBinding_USCOREIOGServiceProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes non-shared managing context only (use destroy() to delete deserialized data)
        virtual ~BasicHttpBinding_USCOREIOGServiceProxy();
        /// Initializer used by constructors
        virtual void BasicHttpBinding_USCOREIOGServiceProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual BasicHttpBinding_USCOREIOGServiceProxy *copy() SOAP_PURE_VIRTUAL;
        /// Copy assignment
        BasicHttpBinding_USCOREIOGServiceProxy& operator=(const BasicHttpBinding_USCOREIOGServiceProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault string (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail as string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        /// Web service operation 'GetGloves' (returns SOAP_OK or error code)
        virtual int GetGloves(_ns1__GetGloves *ns1__GetGloves, _ns1__GetGlovesResponse &ns1__GetGlovesResponse)
        { return this->GetGloves(NULL, NULL, ns1__GetGloves, ns1__GetGlovesResponse); }
        virtual int GetGloves(const char *soap_endpoint, const char *soap_action, _ns1__GetGloves *ns1__GetGloves, _ns1__GetGlovesResponse &ns1__GetGlovesResponse);
        /// Web service operation 'RefreshGloves' (returns SOAP_OK or error code)
        virtual int RefreshGloves(_ns1__RefreshGloves *ns1__RefreshGloves, _ns1__RefreshGlovesResponse &ns1__RefreshGlovesResponse)
        { return this->RefreshGloves(NULL, NULL, ns1__RefreshGloves, ns1__RefreshGlovesResponse); }
        virtual int RefreshGloves(const char *soap_endpoint, const char *soap_action, _ns1__RefreshGloves *ns1__RefreshGloves, _ns1__RefreshGlovesResponse &ns1__RefreshGlovesResponse);
        /// Web service operation 'SaveGlove' (returns SOAP_OK or error code)
        virtual int SaveGlove(_ns1__SaveGlove *ns1__SaveGlove, _ns1__SaveGloveResponse &ns1__SaveGloveResponse)
        { return this->SaveGlove(NULL, NULL, ns1__SaveGlove, ns1__SaveGloveResponse); }
        virtual int SaveGlove(const char *soap_endpoint, const char *soap_action, _ns1__SaveGlove *ns1__SaveGlove, _ns1__SaveGloveResponse &ns1__SaveGloveResponse);
        /// Web service operation 'Activate' (returns SOAP_OK or error code)
        virtual int Activate(_ns1__Activate *ns1__Activate, _ns1__ActivateResponse &ns1__ActivateResponse)
        { return this->Activate(NULL, NULL, ns1__Activate, ns1__ActivateResponse); }
        virtual int Activate(const char *soap_endpoint, const char *soap_action, _ns1__Activate *ns1__Activate, _ns1__ActivateResponse &ns1__ActivateResponse);
        /// Web service operation 'Connect' (returns SOAP_OK or error code)
        virtual int Connect(_ns1__Connect *ns1__Connect, _ns1__ConnectResponse &ns1__ConnectResponse)
        { return this->Connect(NULL, NULL, ns1__Connect, ns1__ConnectResponse); }
        virtual int Connect(const char *soap_endpoint, const char *soap_action, _ns1__Connect *ns1__Connect, _ns1__ConnectResponse &ns1__ConnectResponse);
        /// Web service operation 'Disconnect' (returns SOAP_OK or error code)
        virtual int Disconnect(_ns1__Disconnect *ns1__Disconnect, _ns1__DisconnectResponse &ns1__DisconnectResponse)
        { return this->Disconnect(NULL, NULL, ns1__Disconnect, ns1__DisconnectResponse); }
        virtual int Disconnect(const char *soap_endpoint, const char *soap_action, _ns1__Disconnect *ns1__Disconnect, _ns1__DisconnectResponse &ns1__DisconnectResponse);
        /// Web service operation 'ActivateMany' (returns SOAP_OK or error code)
        virtual int ActivateMany(_ns1__ActivateMany *ns1__ActivateMany, _ns1__ActivateManyResponse &ns1__ActivateManyResponse)
        { return this->ActivateMany(NULL, NULL, ns1__ActivateMany, ns1__ActivateManyResponse); }
        virtual int ActivateMany(const char *soap_endpoint, const char *soap_action, _ns1__ActivateMany *ns1__ActivateMany, _ns1__ActivateManyResponse &ns1__ActivateManyResponse);
        /// Web service operation 'addFlexor' (returns SOAP_OK or error code)
        virtual int addFlexor(_ns1__addFlexor *ns1__addFlexor, _ns1__addFlexorResponse &ns1__addFlexorResponse)
        { return this->addFlexor(NULL, NULL, ns1__addFlexor, ns1__addFlexorResponse); }
        virtual int addFlexor(const char *soap_endpoint, const char *soap_action, _ns1__addFlexor *ns1__addFlexor, _ns1__addFlexorResponse &ns1__addFlexorResponse);
        /// Web service operation 'removeFlexor' (returns SOAP_OK or error code)
        virtual int removeFlexor(_ns1__removeFlexor *ns1__removeFlexor, _ns1__removeFlexorResponse &ns1__removeFlexorResponse)
        { return this->removeFlexor(NULL, NULL, ns1__removeFlexor, ns1__removeFlexorResponse); }
        virtual int removeFlexor(const char *soap_endpoint, const char *soap_action, _ns1__removeFlexor *ns1__removeFlexor, _ns1__removeFlexorResponse &ns1__removeFlexorResponse);
        /// Web service operation 'calibrateFlexors' (returns SOAP_OK or error code)
        virtual int calibrateFlexors(_ns1__calibrateFlexors *ns1__calibrateFlexors, _ns1__calibrateFlexorsResponse &ns1__calibrateFlexorsResponse)
        { return this->calibrateFlexors(NULL, NULL, ns1__calibrateFlexors, ns1__calibrateFlexorsResponse); }
        virtual int calibrateFlexors(const char *soap_endpoint, const char *soap_action, _ns1__calibrateFlexors *ns1__calibrateFlexors, _ns1__calibrateFlexorsResponse &ns1__calibrateFlexorsResponse);
        /// Web service operation 'confirmCalibration' (returns SOAP_OK or error code)
        virtual int confirmCalibration(_ns1__confirmCalibration *ns1__confirmCalibration, _ns1__confirmCalibrationResponse &ns1__confirmCalibrationResponse)
        { return this->confirmCalibration(NULL, NULL, ns1__confirmCalibration, ns1__confirmCalibrationResponse); }
        virtual int confirmCalibration(const char *soap_endpoint, const char *soap_action, _ns1__confirmCalibration *ns1__confirmCalibration, _ns1__confirmCalibrationResponse &ns1__confirmCalibrationResponse);
        /// Web service operation 'setThreshold' (returns SOAP_OK or error code)
        virtual int setThreshold(_ns1__setThreshold *ns1__setThreshold, _ns1__setThresholdResponse &ns1__setThresholdResponse)
        { return this->setThreshold(NULL, NULL, ns1__setThreshold, ns1__setThresholdResponse); }
        virtual int setThreshold(const char *soap_endpoint, const char *soap_action, _ns1__setThreshold *ns1__setThreshold, _ns1__setThresholdResponse &ns1__setThresholdResponse);
        /// Web service operation 'resetFlexors' (returns SOAP_OK or error code)
        virtual int resetFlexors(_ns1__resetFlexors *ns1__resetFlexors, _ns1__resetFlexorsResponse &ns1__resetFlexorsResponse)
        { return this->resetFlexors(NULL, NULL, ns1__resetFlexors, ns1__resetFlexorsResponse); }
        virtual int resetFlexors(const char *soap_endpoint, const char *soap_action, _ns1__resetFlexors *ns1__resetFlexors, _ns1__resetFlexorsResponse &ns1__resetFlexorsResponse);
        /// Web service operation 'startIMU' (returns SOAP_OK or error code)
        virtual int startIMU(_ns1__startIMU *ns1__startIMU, _ns1__startIMUResponse &ns1__startIMUResponse)
        { return this->startIMU(NULL, NULL, ns1__startIMU, ns1__startIMUResponse); }
        virtual int startIMU(const char *soap_endpoint, const char *soap_action, _ns1__startIMU *ns1__startIMU, _ns1__startIMUResponse &ns1__startIMUResponse);
        /// Web service operation 'setIMUStatus' (returns SOAP_OK or error code)
        virtual int setIMUStatus(_ns1__setIMUStatus *ns1__setIMUStatus, _ns1__setIMUStatusResponse &ns1__setIMUStatusResponse)
        { return this->setIMUStatus(NULL, NULL, ns1__setIMUStatus, ns1__setIMUStatusResponse); }
        virtual int setIMUStatus(const char *soap_endpoint, const char *soap_action, _ns1__setIMUStatus *ns1__setIMUStatus, _ns1__setIMUStatusResponse &ns1__setIMUStatusResponse);
        /// Web service operation 'setRawData' (returns SOAP_OK or error code)
        virtual int setRawData(_ns1__setRawData *ns1__setRawData, _ns1__setRawDataResponse &ns1__setRawDataResponse)
        { return this->setRawData(NULL, NULL, ns1__setRawData, ns1__setRawDataResponse); }
        virtual int setRawData(const char *soap_endpoint, const char *soap_action, _ns1__setRawData *ns1__setRawData, _ns1__setRawDataResponse &ns1__setRawDataResponse);
    };
#endif
